import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "@/components/ui/Logo";
import { Nav } from "@/components/ui/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "altroom",
  description: "Generated by create next app",
  openGraph: {
    title: "altroom",
    description: "Generated by create next app",
    images: [
      {
        url: "/image/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "altroom",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "altroom",
    description: "Generated by create next app",
    images: ["/image/og-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Logo />
      <Nav />
        {children}
      </body>
    </html>
  );
}
